### PR TITLE
fix(example) updateQueries in optimistic-ui.md

### PR DESCRIPTION
**Pull request by acramatte**

### CODE REVIEW

**Comment by Urigo** [comment]
@acramatte thank you!  can you please change the other variables to be `previousResult` instead of changing everything to `prev`?
I think it will be easier for new people to understand
Thhanks!

**Comment by acramatte** [comment]
@Urigo I wasn't too sure which one to use so I went with `prev` because that's what is used in other examples. I'll update the PR then :)

**Comment by Urigo** [comment]
great! waiting for it

**Comment by Urigo** [comment]
thank you @acramatte !

**Pull request merged**
